title: <p align="center"> Sneha Kumari </p>
logo: assets/Sneha_dp_cropped.jpg

description: 
<p align="center">

<br>
I am a Data Scientist Enthusiast and looking for a transition in Data Science domain. 
<br>
</p>

# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
