title: <p align="center"> Sneha Kumari </p>
logo: /assets/img/logo.png
description: I am a Data Scientist Enthusiast and looking for a transition in Data Science domain. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
